environment: production

connectors:
  - file: connectorRIS
    name: ris
    params:
      carefulSubscription: false
      url: wss://ris-live.ripe.net/v1/ws/
      subscription:
        moreSpecific: true
        type: UPDATE
        host:
        socketOptions:
          includeRaw: false

monitors:
  - file: monitorHijack
    channel: hijack
    name: basic-hijack-detection

  - file: monitorNewPrefix
    channel: newprefix
    name: prefix-detection

  - file: monitorVisibility
    channel: visibility
    name: withdrawal-detection
    params:
      threshold: 0

reports:
  - file: reportFile
    channels:
      - hijack
      - newprefix
      - visibility

  - file: ReportEmail
    channels:
      - hijack
      - newprefix
      - visibility

  - file: ReportSlack
    channels:
      - hijack
      - newprefix
      - visibility
    params:
      hookUrl: https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXXXXXXXXX


checkStaleNotificationsSeconds: 60
notificationIntervalSeconds: 1800 # Repeat the same alert (which keeps being triggered) after x seconds
clearNotificationQueueAfterSeconds: 1900 # Stop with the alert for an event which didn't happen again in x seconds

# The file containing the monitored prefixes. Please see monitored_prefixes_test.yml for an example
# This is an array (use new lines and dashes!)
monitoredPrefixesFiles:
  - prefixes.yml

logging:
  directory: logs
  logRotatePattern: YYYY-MM-DD  # Whenever the pattern changes, a new file is created and the old one rotated
  zippedArchive: true
  maxSize: 20m
  maxFiles: 14d